name: build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Make the output directories
        run: mkdir -p build/{a4,letter,svg}
      - name: Build A4 PDF
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"a4\" -o build/a4 guitar-chord-chart-standard-tuning.ly
      - name: Build Letter PDF
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"letter\" -o build/letter guitar-chord-chart-standard-tuning.ly
      - name: Build SVG
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond --svg -dno-point-and-click -dpaper-size=\"a4\" -o build/svg guitar-chord-chart-standard-tuning.ly
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Upload A4 artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: a4-${{ steps.slug.outputs.sha7 }}
          path: build/a4
      - name: Upload Letter artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: letter-${{ steps.slug.outputs.sha7 }}
          path: build/letter
      - name: Upload SVG artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: svg-${{ steps.slug.outputs.sha7 }}
          path: build/svg
