name: deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Checkout the Jekyll template
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          path: build
          repository: jeandeaual/lilypond-jekyll-template
      # Output folders (a4, letter and svg) are included in .gitignore, preventing them to be commited to the gh_pages branch
      - name: Remove the .gitignore file
        run: rm build/.gitignore
      - name: Make the output directories
        run: mkdir -p build/{a4,letter,svg}
      - name: Build A4 PDF (guitar)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"a4\" -o build/a4 guitar-chord-chart-standard-tuning.ly
      - name: Build Letter PDF (guitar)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"letter\" -o build/letter guitar-chord-chart-standard-tuning.ly
      - name: Build SVG (guitar)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond --svg -dno-point-and-click -dpaper-size=\"a4\" -o build/svg guitar-chord-chart-standard-tuning.ly
      - name: Build A4 PDF (ukulele)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"a4\" -o build/a4 ukulele-chord-chart-a-e-c-g-tuning.ly
      - name: Build Letter PDF (ukulele)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"letter\" -o build/letter ukulele-chord-chart-a-e-c-g-tuning.ly
      - name: Build SVG (ukulele)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond --svg -dno-point-and-click -dpaper-size=\"a4\" -o build/svg ukulele-chord-chart-a-e-c-g-tuning.ly
      - name: Build A4 PDF (mandolin)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"a4\" -o build/a4 mandolin-chord-chart-standard-tuning.ly
      - name: Build Letter PDF (mandolin)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond -dno-point-and-click -dembed-source-code -dpaper-size=\"letter\" -o build/letter mandolin-chord-chart-standard-tuning.ly
      - name: Build SVG (mandolin)
        uses: docker://jeandeaual/lilypond:latest
        with:
          args: lilypond --svg -dno-point-and-click -dpaper-size=\"a4\" -o build/svg mandolin-chord-chart-standard-tuning.ly
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Upload A4 artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: a4-${{ steps.slug.outputs.sha7 }}
          path: build/a4
      - name: Upload Letter artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: letter-${{ steps.slug.outputs.sha7 }}
          path: build/letter
      - name: Upload SVG artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: svg-${{ steps.slug.outputs.sha7 }}
          path: build/svg
      - name: Update the Jekyll config
        uses: mikefarah/yq@3.4.1
        with:
          cmd: yq w -i -s config.yml build/_config.yml
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          PRESERVE: true
